version: "3"
services:
  web:
    container_name: "web-app"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/root
    restart: always
    depends_on:
      - db
  db:
    container_name: "db"
    image: "mysql"
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp
    restart: always
    volumes:
      - web-data:/var/lib/mysql
volumes:
  web-data:
